name: pinch_zoom_image_last
description: Pinch Zoom Image package last fixed version.
version: 0.3.0
author: Furkan KURT <fkurt97@gmail.com>
homepage: https://github.com/furkankurt/pinch_zoom_image_last

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: